package com.backend.authsystem.authentication.enums;

public enum PermissionEnum {

    //User-level permissions

    //profile-level
    PROFILE_VIEW, //(USER)
    PROFILE_UPDATE, //(USER)
    ACCOUNT_VIEW, //(USER)
    PASSWORD_CHANGE, //(USER)

    // lecturer-level
    // course
    COURSE_ENROLLMENT_COUNT,
    COURSE_ENROLLMENT_LIST,
    COURSE_ENROLLMENT,
    COURSE_CREATE, //(LECTURER)
    COURSE_UPDATE, //(LECTURER)
    COURSE_PUBLISH, //(LECTURER)
    COURSE_OPEN_ENROLLMENT, //(LECTURER)
    COURSE_CLOSE_ENROLLMENT, //(LECTURER)
    COURSE_START, //(LECTURER)
    COURSE_COMPLETE, //(LECTURER)
    COURSE_ARCHIVE, //(STUDENT)
    COURSE_VIEW, //(LECTURER, STUDENT)
    COURSE_VIEW_ALL, //(LECTURER, STUDENT)


    // assignment
    ASSIGNMENT_CREATE, // LECTURER
    ASSIGNMENT_UPDATE, // LECTURER
    ASSIGNMENT_VIEW, // LECTURER, STUDENT
    ASSIGNMENT_SUBMIT, // STUDENT
    ASSIGNMENT_PUBLISH, // LECTURER
    ASSIGNMENT_SUBMISSION_CLOSE, // LECTURER
    ASSIGNMENT_START_GRADING, // LECTURER
    ASSIGNMENT_MARK_GRADED, // LECTURER
    ASSIGNMENT_ARCHIVE, // LECTURER


    ASSIGNMENT_SUBMISSION_VIEW,
    ASSIGNMENT_SUBMISSION_VIEW_ALL,
    ASSIGNMENT_GRADE,

    CLASS_FEEDBACK_VIEW,
    CLASS_ANNOUNCEMENT_CREATE,

    // student-level
    COURSE_MATERIAL_VIEW,
    CLASS_FEEDBACK_SUBMIT,
    GENERAL_ANNOUNCEMENT_VIEW,


    // course rep-level
    CLASS_ANNOUNCEMENT_VIEW,
    CLASS_ANNOUNCEMENT_RELAY,
    CLASS_FEEDBACK_COLLECT,
    CLASS_FEEDBACK_FORWARD,

    // materials
    COURSE_MATERIAL_CREATE,
    COURSE_MATERIAL_UPDATE,
    COURSE_MATERIAL_DELETE,

//    ENROLLED STUDENTS_VIEW,


    // admin-level (system)
    ROLE_ASSIGN, //(ADMIN)
    PERMISSION_ASSIGN, //(ADMIN)
    USER_MANAGE

}
