
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Swagger Configuration
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# For prod environment: see prod logs
logging.level.com.backend.authsystem.authentication.service=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n


file.upload.directory=/app/uploads
file.upload.max-size-assignment=10MB
file.upload.max-size-course-material=200MB

admin.firstname=${ADMIN_FIRST_NAME}
admin.lastname=${ADMIN_LAST_NAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}